"""
Security Report Generator

Generates comprehensive security audit reports.
"""

from typing import List, Dict, Optional
from datetime import datetime
import json


class SecurityReport:
    """
    Generates formatted security audit reports
    """

    def __init__(self):
        pass

    def generate_report(
        self,
        workflow: Dict,
        score: 'SecurityScore',
        secret_findings: List,
        auth_findings: List,
        exposure_findings: List,
        format: str = "markdown"
    ) -> str:
        """
        Generate formatted security report

        Args:
            workflow: Workflow dict
            score: SecurityScore object
            secret_findings: Secret detection findings
            auth_findings: Authentication findings
            exposure_findings: Exposure findings
            format: Report format (markdown, json, text)

        Returns:
            Formatted report string
        """
        if format == "json":
            return self._generate_json_report(
                workflow, score, secret_findings, auth_findings, exposure_findings
            )
        elif format == "text":
            return self._generate_text_report(
                workflow, score, secret_findings, auth_findings, exposure_findings
            )
        else:  # markdown (default)
            return self._generate_markdown_report(
                workflow, score, secret_findings, auth_findings, exposure_findings
            )

    def _generate_markdown_report(
        self,
        workflow: Dict,
        score: 'SecurityScore',
        secret_findings: List,
        auth_findings: List,
        exposure_findings: List
    ) -> str:
        """Generate markdown formatted report"""
        workflow_name = workflow.get("name", "Unknown Workflow")
        workflow_id = workflow.get("id", "unknown")

        # Report header
        report = f"""# 🔐 Security Audit Report

**Workflow:** {workflow_name}
**Workflow ID:** `{workflow_id}`
**Audit Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Report Generated By:** n8n Workflow Builder Security Auditor

---

## 📊 Security Score

**Score:** {score.score}/100 ({score._get_grade()})
**Risk Level:** {self._get_risk_emoji(score.risk_level.value)} **{score.risk_level.value.upper()}**

### Score Breakdown
"""

        # Score breakdown
        if score.deductions:
            report += "```\n"
            for category, deduction in score.deductions.items():
                report += f"{category.capitalize():<20} -{deduction:>3} points\n"
            report += "```\n\n"

        # Findings summary
        report += "### Findings Summary\n\n"
        report += f"- 🔴 **Critical:** {score.findings_count['critical']} findings\n"
        report += f"- 🟠 **High:** {score.findings_count['high']} findings\n"
        report += f"- 🟡 **Medium:** {score.findings_count['medium']} findings\n"
        report += f"- 🟢 **Low:** {score.findings_count['low']} findings\n"
        report += f"\n**Total:** {sum(score.findings_count.values())} security issues found\n\n"

        # Overall assessment
        report += self._get_assessment(score)

        report += "\n---\n\n"

        # Detailed findings sections
        if secret_findings:
            report += self._format_secret_findings(secret_findings)

        if auth_findings:
            report += self._format_auth_findings(auth_findings)

        if exposure_findings:
            report += self._format_exposure_findings(exposure_findings)

        # Recommendations section
        report += self._generate_recommendations(
            score, secret_findings, auth_findings, exposure_findings
        )

        # Footer
        report += "\n---\n\n"
        report += "*This report was generated automatically by the n8n Workflow Builder Security Auditor.*  \n"
        report += "*For questions or false positives, please review the findings manually.*\n"

        return report

    def _format_secret_findings(self, findings: List) -> str:
        """Format secret detection findings"""
        report = "## 🔑 Hardcoded Secrets Detected\n\n"
        report += f"**Total:** {len(findings)} secret(s) found\n\n"

        # Group by severity
        by_severity = self._group_by_severity(findings)

        for severity in ["critical", "high", "medium", "low"]:
            items = by_severity.get(severity, [])
            if not items:
                continue

            emoji = self._get_severity_emoji(severity)
            report += f"### {emoji} {severity.upper()} Severity ({len(items)} finding(s))\n\n"

            for i, finding in enumerate(items, 1):
                report += f"#### {i}. {finding.secret_type.value.replace('_', ' ').title()}\n\n"
                report += f"**Node:** `{finding.node_name}` ({finding.node_id})\n"
                report += f"**Field:** `{finding.field_path}`\n"
                report += f"**Value Preview:** `{finding.value_preview}`\n"
                report += f"**Confidence:** {finding.confidence:.0%}\n\n"
                report += f"**Recommendation:** {finding.recommendation}\n\n"

        return report

    def _format_auth_findings(self, findings: List) -> str:
        """Format authentication findings"""
        report = "## 🔒 Authentication Issues\n\n"
        report += f"**Total:** {len(findings)} authentication issue(s) found\n\n"

        by_severity = self._group_by_severity(findings)

        for severity in ["critical", "high", "medium", "low"]:
            items = by_severity.get(severity, [])
            if not items:
                continue

            emoji = self._get_severity_emoji(severity)
            report += f"### {emoji} {severity.upper()} Severity ({len(items)} finding(s))\n\n"

            for i, finding in enumerate(items, 1):
                report += f"#### {i}. {finding.issue_type.value.replace('_', ' ').title()}\n\n"
                report += f"**Node:** `{finding.node_name}` ({finding.node_type})\n"
                report += f"**Description:** {finding.description}\n"
                if finding.affected_field:
                    report += f"**Affected Field:** `{finding.affected_field}`\n"
                report += f"\n**Recommendation:** {finding.recommendation}\n\n"

        return report

    def _format_exposure_findings(self, findings: List) -> str:
        """Format exposure findings"""
        report = "## 🌐 Exposure Risks\n\n"
        report += f"**Total:** {len(findings)} exposure risk(s) found\n\n"

        by_severity = self._group_by_severity(findings)

        for severity in ["critical", "high", "medium", "low"]:
            items = by_severity.get(severity, [])
            if not items:
                continue

            emoji = self._get_severity_emoji(severity)
            report += f"### {emoji} {severity.upper()} Severity ({len(items)} finding(s))\n\n"

            for i, finding in enumerate(items, 1):
                report += f"#### {i}. {finding.exposure_type.value.replace('_', ' ').title()}\n\n"
                report += f"**Node:** `{finding.node_name}` ({finding.node_type})\n"
                report += f"**Description:** {finding.description}\n"
                report += f"**Risk:** {finding.risk}\n"
                if finding.exposed_data:
                    report += f"**Exposed Data:** {', '.join(finding.exposed_data)}\n"
                if finding.affected_field:
                    report += f"**Affected Field:** `{finding.affected_field}`\n"
                report += f"\n**Recommendation:** {finding.recommendation}\n\n"

        return report

    def _generate_recommendations(
        self,
        score: 'SecurityScore',
        secret_findings: List,
        auth_findings: List,
        exposure_findings: List
    ) -> str:
        """Generate prioritized recommendations"""
        report = "## 💡 Prioritized Recommendations\n\n"

        if score.risk_level.value == "critical":
            report += "⚠️  **URGENT**: Your workflow has critical security issues that must be addressed immediately.\n\n"
        elif score.risk_level.value == "high":
            report += "⚠️  **Important**: Your workflow has significant security issues that should be fixed soon.\n\n"

        # Top 3 recommendations
        recommendations = []

        if secret_findings:
            recommendations.append(
                "**1. Remove Hardcoded Secrets:** Replace all hardcoded API keys, passwords, and tokens with n8n credentials."
            )

        if auth_findings:
            recommendations.append(
                f"**{len(recommendations) + 1}. Fix Authentication Issues:** Enable authentication on webhooks and secure all external connections."
            )

        if exposure_findings:
            recommendations.append(
                f"**{len(recommendations) + 1}. Reduce Exposure:** Add authentication to public endpoints and filter sensitive data in responses."
            )

        if not recommendations:
            report += "✅ No critical recommendations - your workflow follows security best practices!\n\n"
        else:
            for rec in recommendations:
                report += f"{rec}\n\n"

        return report

    def _generate_json_report(
        self,
        workflow: Dict,
        score: 'SecurityScore',
        secret_findings: List,
        auth_findings: List,
        exposure_findings: List
    ) -> str:
        """Generate JSON formatted report"""
        report_data = {
            "workflow": {
                "id": workflow.get("id"),
                "name": workflow.get("name"),
            },
            "audit": {
                "timestamp": datetime.now().isoformat(),
                "version": "1.0.0"
            },
            "score": score.to_dict(),
            "findings": {
                "secrets": [f.to_dict() for f in secret_findings],
                "authentication": [f.to_dict() for f in auth_findings],
                "exposure": [f.to_dict() for f in exposure_findings]
            }
        }

        return json.dumps(report_data, indent=2)

    def _generate_text_report(
        self,
        workflow: Dict,
        score: 'SecurityScore',
        secret_findings: List,
        auth_findings: List,
        exposure_findings: List
    ) -> str:
        """Generate plain text report"""
        report = "=" * 80 + "\n"
        report += "SECURITY AUDIT REPORT\n"
        report += "=" * 80 + "\n\n"

        report += f"Workflow: {workflow.get('name', 'Unknown')}\n"
        report += f"Workflow ID: {workflow.get('id', 'unknown')}\n"
        report += f"Audit Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

        report += "-" * 80 + "\n"
        report += "SECURITY SCORE\n"
        report += "-" * 80 + "\n\n"

        report += f"Score: {score.score}/100 ({score._get_grade()})\n"
        report += f"Risk Level: {score.risk_level.value.upper()}\n\n"

        report += "Findings Summary:\n"
        report += f"  Critical: {score.findings_count['critical']}\n"
        report += f"  High:     {score.findings_count['high']}\n"
        report += f"  Medium:   {score.findings_count['medium']}\n"
        report += f"  Low:      {score.findings_count['low']}\n"
        report += f"  Total:    {sum(score.findings_count.values())}\n\n"

        if secret_findings:
            report += "-" * 80 + "\n"
            report += f"HARDCODED SECRETS ({len(secret_findings)} found)\n"
            report += "-" * 80 + "\n\n"

            for i, finding in enumerate(secret_findings, 1):
                report += f"{i}. {finding.secret_type.value} in {finding.node_name}\n"
                report += f"   Field: {finding.field_path}\n"
                report += f"   Recommendation: {finding.recommendation}\n\n"

        if auth_findings:
            report += "-" * 80 + "\n"
            report += f"AUTHENTICATION ISSUES ({len(auth_findings)} found)\n"
            report += "-" * 80 + "\n\n"

            for i, finding in enumerate(auth_findings, 1):
                report += f"{i}. {finding.issue_type.value} in {finding.node_name}\n"
                report += f"   {finding.description}\n"
                report += f"   Recommendation: {finding.recommendation}\n\n"

        if exposure_findings:
            report += "-" * 80 + "\n"
            report += f"EXPOSURE RISKS ({len(exposure_findings)} found)\n"
            report += "-" * 80 + "\n\n"

            for i, finding in enumerate(exposure_findings, 1):
                report += f"{i}. {finding.exposure_type.value} in {finding.node_name}\n"
                report += f"   Risk: {finding.risk}\n"
                report += f"   Recommendation: {finding.recommendation}\n\n"

        report += "=" * 80 + "\n"
        return report

    def _group_by_severity(self, findings: List) -> Dict[str, List]:
        """Group findings by severity"""
        grouped = {
            "critical": [],
            "high": [],
            "medium": [],
            "low": []
        }

        for finding in findings:
            severity = finding.severity.value if hasattr(finding.severity, 'value') else finding.severity
            if severity in grouped:
                grouped[severity].append(finding)

        return grouped

    def _get_severity_emoji(self, severity: str) -> str:
        """Get emoji for severity"""
        return {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🟢"
        }.get(severity, "⚪")

    def _get_risk_emoji(self, risk_level: str) -> str:
        """Get emoji for risk level"""
        return {
            "critical": "🚨",
            "high": "⚠️",
            "medium": "⚡",
            "low": "✅",
            "excellent": "🌟"
        }.get(risk_level, "❓")

    def _get_assessment(self, score: 'SecurityScore') -> str:
        """Get overall security assessment"""
        assessments = {
            "critical": "🚨 **CRITICAL**: This workflow has severe security vulnerabilities that pose immediate risk. Address critical issues immediately.",
            "high": "⚠️ **HIGH RISK**: This workflow has significant security issues that should be fixed as soon as possible.",
            "medium": "⚡ **MODERATE RISK**: This workflow has some security concerns that should be addressed.",
            "low": "✅ **LOW RISK**: This workflow follows most security best practices but has minor improvements possible.",
            "excellent": "🌟 **EXCELLENT**: This workflow follows security best practices!"
        }

        return f"\n### Overall Assessment\n\n{assessments.get(score.risk_level.value, 'Assessment unavailable')}\n"
